-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'FARMER';
ALTER TYPE "Role" ADD VALUE 'SUPPLIER';

-- AlterTable
ALTER TABLE "User" 
ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN "firstLogin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "farmSize" DOUBLE PRECISION,
ADD COLUMN "companyName" TEXT,
ADD COLUMN "businessRegNo" TEXT,
ADD COLUMN "location" TEXT;